### ISSUE TITLE
code

### ISSUE THREAD

**Issue by lameinthebox** [SWPP/cid-backend#18]
Muser model에 추가
![screenshot from 2018-12-17 00-13-35](https://user-images.githubusercontent.com/19164119/50055338-e4f9b800-0190-11e9-9a47-91ce1b1e8851.png)

tasks.py에 추가
![screenshot from 2018-12-17 00-11-24](https://user-images.githubusercontent.com/19164119/50055291-63098f00-0190-11e9-8610-0ce9f5d41b92.png)

**Comment by holenet** [comment]
max_length 200 은 너무 안일하네요
500은 해야죠

**Comment by holenet** [comment]
![image](https://user-images.githubusercontent.com/24453019/50055441-7158aa80-0192-11e9-8022-1ab52c2a66ea.png)
이부분 이해가 가지 않습니다.
`genres`를 왜 두번 연속 assign 하는거죠?

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 00-29-59](https://user-images.githubusercontent.com/19164119/50055476-e88e3e80-0192-11e9-98aa-4f8dc2ab62f7.png)

+가 빠졌었네요

**Comment by holenet** [comment]
실제로 존재하지 않는 장르는 넣지 않아야 한다고 생각합니다.
`fan_genres`의 길이가 무한정으로 늘어날 수 있기 때문에 제약이 필요합니다.

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 00-33-37](https://user-images.githubusercontent.com/19164119/50055505-68b4a400-0193-11e9-9bb8-aefae0bfae8d.png)

**Comment by holenet** [comment]
제대로 되려나요...
music의 genre는 여러 genre가 `,` 와 `/` 합쳐져 있는데 잘 될지 의문입니다.

그리고 `fan_genre`의 길이가 무한정 늘어날 수 있는 문제는 해결되지 않았습니다.

또한, 해당하는 `aritst`나 `genre`를 찾지 못했을 경우에는 적절하게 `text`를 변경해야 할 것 같습니다.

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 00-42-14](https://user-images.githubusercontent.com/19164119/50055625-a0701b80-0194-11e9-87e0-348921c09190.png)

**Comment by holenet** [comment]
`What kind of ...` 의 경우에는 유저가 어떻게 대답하기를 기대하는 겁니까?

**Comment by lameinthebox** [comment]
걍 아무 말이나 하지 않을까?
챗봇은 무시하면 되고

**Comment by holenet** [comment]
그리고 70번째줄에서 `name`과 `'name'`은 잘못 쓰인 것 같습니다.

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 00-47-45](https://user-images.githubusercontent.com/19164119/50055683-618e9580-0195-11e9-95ef-e26b9aa7ad6c.png)

**Comment by holenet** [comment]
그래도 이상합니다.
```python3
music = Music.objects.filter(genre__trigram_similar=genre_name).annotate(similarity=TrigramSimilarity('genre', genre_name)).order_by('-similarity').first()
```
가 맞을 듯 합니다.
보아하니 비슷하게 63번째 줄도 고쳐야 할 듯 하군요.

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 00-52-48](https://user-images.githubusercontent.com/19164119/50055731-17f27a80-0196-11e9-90f6-35484d03059a.png)

**Comment by holenet** [comment]
괜찮은듯합니다.

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 01-18-25](https://user-images.githubusercontent.com/19164119/50056011-acaaa780-0199-11e9-820b-0d73d42229fb.png)

**Comment by holenet** [comment]
`c.genre`는 `,`와 `/`로 구분되는 장르 스트링의 집합입니다. 저대로면 장르에 의해 점수가 높아지는 일은 별로 없을 것입니다.

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 01-28-50](https://user-images.githubusercontent.com/19164119/50056121-1f685280-019b-11e9-8daa-577fb2ac430d.png)

**Comment by holenet** [comment]
`.strip()` 을 추가하는게 좋습니다.

**Comment by lameinthebox** [comment]
어디에?

**Comment by holenet** [comment]
또, `user.fan_artists.all()` 로 바꾸는게 안전할 것 같습니다.
원래 코드가 가능한 구문인지 아닌지 확신이 서지 않습니다.

**Comment by holenet** [comment]
34 번째 줄에 `if g.strip() in ...`

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 01-34-09](https://user-images.githubusercontent.com/19164119/50056172-de247280-019b-11e9-89ee-eaddc0fa9a4a.png)

**Comment by holenet** [comment]
`.all()` 해달라니까..

**Comment by lameinthebox** [comment]
![screenshot from 2018-12-17 01-37-49](https://user-images.githubusercontent.com/19164119/50056201-60149b80-019c-11e9-9e32-71907d9f6053.png)

**Comment by holenet** [comment]
굿

**Comment by holenet** [comment]
```python3
# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': None,
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
```
`settings.py`에 붙여넣으세요

**Comment by holenet** [comment]
## Introduction
> 사람들은 자신의 취향에 맞는 음악을 듣고 싶어 합니다. 그러나 그런 음악들을 찾는 것을 쉬운 일이 아니죠.
그러므로, 큰 노력을 들이지 않고 좋은 노래를 찾는 일은 매우 만족스러운 경험이 될 것입니다. 저희는 유저의 입맛을 분석하여 각각의 유저을 즐겁게 해줄 음악을 추천해 주는 서비스를 개발했습니다. 또한, 저희는 유저들이 챗봇과의 채팅을 통하여 음악을 추천 받을 수 있도록 메시지 커뮤니케이션 시스템을 구축하였습니다.
저희들의 서비스 이름인 Mubot(뮤봇)은 music과 chatbot의 합성어입니다. 뮤봇은 유저들이 이전에 평가한 기록들을 가지고서 Collaborative Filtering 기법을 이용하여 유저들에게 음악을 추천해 줄 것입니다. 물론, 자연어를 이용한 채팅으로써 말이죠.

## Interface
![interface](https://user-images.githubusercontent.com/24453019/50056445-b6370e00-019f-11e9-937f-08673938bc76.PNG)

## Structure
![structure](https://user-images.githubusercontent.com/24453019/50056444-b20af080-019f-11e9-9b15-88e0fab111b2.PNG)

## Images
![icon](https://user-images.githubusercontent.com/24453019/50056452-c6e78400-019f-11e9-88e8-7763239d9a07.png)
![title](https://user-images.githubusercontent.com/24453019/50056453-c6e78400-019f-11e9-83d3-7c2594bc94dc.png)
![title_detail](https://user-images.githubusercontent.com/24453019/50056454-c6e78400-019f-11e9-85bd-4b3a3f9dff86.png)

**Comment by Tommybro** [comment]
인터페이스 맨 왼쪽 사진에 user 입력중에 nice보다 so so가 더 자연스러운 것 같습니다.
원래 nice가 good과 같이 좋은 일 있냐고 묻는 반응이 나와야 하는데 이상하게 nice라는 단어를 인식하지를 못합니다.
사진 속 Mubot의 반응은 기분이 좋지도 나쁘지도 않은 경우를 대비한 반응입니다.

**Comment by holenet** [comment]
@Tommybro 그래서 어떻게 하라는 거죠?
바꾸라고 할거면 자기가 바꾸세요

**Comment by lameinthebox** [comment]
야 서버 터짐?

**Comment by lameinthebox** [comment]
[poster.pdf](https://github.com/SWPP/cid-backend/files/2683895/poster.pdf)

**Comment by lameinthebox** [comment]
또 터짐?

**Comment by holenet** [comment]
터진건 그렇다 치고 종료시키는데 왤케 안 끝나지

**Comment by holenet** [comment]
자냐?
