### ISSUE TITLE
메일 보내야 한다.

### ISSUE THREAD

**Issue by Tommybro** [SWPP/cid-backend#19]
1. apk
2. 영상
3. 포스터
4. 회사평가표

읽으면 답글좀
현우야 영상 내놔

**Comment by lameinthebox** [comment]
깃헙 레포 링크

**Comment by Tommybro** [comment]
현우가 안일어남

**Comment by lameinthebox** [comment]
전화해

**Comment by Tommybro** [comment]
깨웠음

**Comment by holenet** [comment]
The record file is too big to attach here.
Can I send the file to Tommybro's e-mail?

**Comment by Tommybro** [comment]
![image](https://user-images.githubusercontent.com/19183069/50088375-3152ff80-0246-11e9-965a-805c6e875a92.png)

**Comment by Tommybro** [comment]
예현아 이거 어케하냐?

![image](https://user-images.githubusercontent.com/19183069/50088808-6dd32b00-0247-11e9-82af-bb7f75608ee4.png)

**Comment by Tommybro** [comment]
샘플이 없는데

**Comment by lameinthebox** [comment]
뭘 어떡해? 이거 채점해서 보내는거야?

**Comment by lameinthebox** [comment]
마지막에
한 학기동안 수고하셨습니다
넣어줘

**Comment by holenet** [comment]
담당자가 저거를 채점할 방법이 없잖아

**Comment by lameinthebox** [comment]
저거 애초에 기준이 이상한데?
적중했다는 게 뭐냐?

**Comment by holenet** [comment]
우리가 시뮬레이션해서 맞추겠다는 그런거 아니었엇나
